# Site settings
title: jasonwynn10's Blog
description: "A blog for Pocketmine plugins and programming"
url: "https://jasonwynn10.github.io/blog"
author:
  name: "jasonwynn10"
  email: "jasonwynn10@me.com"
  url: "https://jasonwynn10.github.io"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
